module.exports = app => {
  app.log("on")
  app.on('issues.opened', async context => {
    const {body, user} = context.payload.issue
    const parsedUserHeaders = parseUserHeaders(body)
    const templates = await getAllTemplateContents(context)
    await handleUserHeaders(context, user, parsedUserHeaders, templates)
  })
}

function parseUserHeaders(body) {
  const newlineSeparatedBody = body.replace(/\r\n/g, "\r").replace(/\n/g, "\r").split(/\r/)
  return newlineSeparatedBody.filter(line => line.includes('#'))
}

async function getAllTemplateContents(context) {
  const issueTemplateDirectoryPath = '.github/ISSUE_TEMPLATE'
  const githubTemplatesDirectoryApiRequest = context.repo({path: issueTemplateDirectoryPath})
  const directoryResult = await context.github.repos.getContents(githubTemplatesDirectoryApiRequest)
  return await Promise.all(directoryResult.data.map(async directoryEntry => {
    const templateName = directoryEntry['name']
    const githubTemplatesFilesApiRequest = context.repo({path: `${issueTemplateDirectoryPath}/${templateName}`})
    const filesResult = await context.github.repos.getContents(githubTemplatesFilesApiRequest)
    const body = Buffer.from(filesResult.data.content, 'base64').toString()
    return {
      name: templateName, 
      headers: parseTemplateBody(body)
    }
  }))
}

async function handleUserHeaders(context, user, parsedUserHeaders, templates) {
  let replyNecessary = true
  let templateToUse = {}
  templates.forEach(template => {
    const {_, headers} = template
    if (headers.every(header => parsedUserHeaders.includes(header))) replyNecessary = false
    if (headers.some(header => parsedUserHeaders.includes(header))) templateToUse = template
  })
  if (replyNecessary) postMissingHeaders(context, user, templateToUse)
}

function parseTemplateBody(template) {
  const newlineSeparated = template.replace(/\r\n/g, "\r").replace(/\n/g, "\r").split(/\r/);
  let headers = []
  for (i = 0; i < newlineSeparated.length; i++) {
    const line = newlineSeparated[i]
    if (line.includes('#')) {
      headers.push(line)
    }
  }
  return headers
}

async function postMissingHeaders(context, user, templateToUse) {
  const templatesLink = 'https://github.com/CypherpunkArmory/UserLAnd/issues/new/choose'
  const headersMessage = getHeadersMessage(templateToUse)
  const reply = 
`
Hello @${user.login}!

This message has been autogenerated.

It looks like you've posted an issue, but in order for us to best assist you, we need some additional 
information. We have created some issue templates to make this process easier. You can find them 
[here](${templatesLink}).

These templates contain lines that begin with the '#' character. These lines are **headers**. In 
your issue, please leave these headers **as is**, and fill out information relevant to the header
in the space below it.

If you don't think that you have any information relevant to the header, fill the space below it 
with something like 'N/A', or consider using a different template.

These headers are essential in allowing us to recreate and resolve your issue. The more detailed
your issue, the more quickly we can begin working on it.

${headersMessage}

If your issue is not updated to follow a template, it may be removed.

Thanks for your help in improving UserLAnd!
`

  context.github.issues.createComment(context.issue({body: reply}))
  context.github.issues.addLabels(context.issue({labels: ['more-info-required']}))
}

function getHeadersMessage(templateToUse) {
  if (Object.getOwnPropertyNames(templateToUse).length == 0) {
    return `
This bot could not detect which template you were trying to use. Please follow the link above to
find a template to use.`
  }
  let message = `
It looks like you were attempting to use the ${templateToUse.name} template. Copy and paste the
headers, including the '#' character, remove the single quotes, and use it to edit your issue.
That template requires the following headers:\n\n`
  templateToUse.headers.forEach((header) => 
    message += `'${header}'\n`
  )
  return message
}